### ISSUE TITLE
Crashes on Windows

### ISSUE THREAD

**Issue by hwywhywl** [howie6879/aspider#3]
Traceback (most recent call last):
File "weibospider.py", line 26, in <module>
HackerNewsSpider.start()
File "C:\Users\hwywhywl\StudioProjects\weibo_splider\lib\site-packages\aspider\spider.py", line 92, in start
spider_ins.loop.add_signal_handler(_signal, lambda: asyncio.ensure_future(spider_ins.stop(_signal)))
File "C:\Users\hwywhywl\Anaconda3\lib\asyncio\events.py", line 499, in add_signal_handler
raise NotImplementedError
NotImplementedError

loop.add_signal_handler  is currently not supported on Windows.

**Comment by howie6879** [comment]
Fixed :）
